agent_id = "universal_worker"
version = "1.0.0"
did = "did:aeon:universal_worker:1.0.0:779087511d60d7f0890c6678c034e3024505701cae013aab7633691ecb4d4205"
permissions = ["FS_WRITE", "LOG"]
subscriptions = []
territory = []

[blueprint]

# ==========================================
# üîê GOVERNANCE ORACLE SIGNATURE
# Signed-By: Sovereign (AEON Keyring)
# Public-Key: 779087511d60d7f0890c6678c034e3024505701cae013aab7633691ecb4d4205
# Timestamp: 1769796442 (2026-01-30T23:37:22.434321+05:30)
# Signature: 4dd349aa2a3d5dafcebcec4d82bbc876ffc9683752a8da5569b3435de47d7c3096d9ecbf62ad2dda8876c0eb3bbd9242a513acc83190ba01eb582800c732e70d
# Algorithm: ed25519
# ==========================================
